
import Navbar from "@/components/Navbar";
import "./globals.css";



export const metadata = {
  title: "SpyAndGrow",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased text-white bg-slate-950`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
